// backend/agents/ClaudeAgent.js
import { BaseAgent } from "./BaseAgent.js";
import { estimateCost } from "../pricing.js";

let Anthropic = null;

try {
  const anthropicModule = await import("@anthropic-ai/sdk");
  Anthropic = anthropicModule.default;
} catch (error) {
  // SDK is optional — falls back to mock generation
}

export class ClaudeAgent extends BaseAgent {
  constructor() {
    super("claude", "Anthropic Claude");
    this.client = null;

    if (process.env.ANTHROPIC_API_KEY && Anthropic) {
      try {
        this.client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
        console.log("Claude Agent: client initialized");
      } catch (error) {
        console.warn("Claude Agent: failed to initialize client", error.message);
      }
    } else if (!Anthropic) {
      console.log("Claude Agent: SDK not installed. Using mock generation");
    } else {
      console.log("Claude Agent: no API key. Using mock generation");
    }
  }

  async generate(prompt, modelId) {
    if (this.client) {
      return this._generateWithAPI(prompt, modelId);
    }
    const start = Date.now();
    const output = this._generateWithMock(prompt);
    const latencyMs = Date.now() - start;
    return {
      output,
      metrics: { modelId, inputTokens: null, outputTokens: null, latencyMs, estimatedCostUsd: null },
    };
  }

  async _generateWithAPI(prompt, modelId) {
    const start = Date.now();
    try {
      const message = await this.client.messages.create({
        model: modelId,
        max_tokens: 2000,
        system: this.systemPrompt,
        messages: [{ role: "user", content: prompt }],
      });
      const latencyMs = Date.now() - start;
      const inputTokens = message.usage.input_tokens;
      const outputTokens = message.usage.output_tokens;
      return {
        output: message.content[0].text,
        metrics: {
          modelId,
          inputTokens,
          outputTokens,
          latencyMs,
          estimatedCostUsd: estimateCost(modelId, inputTokens, outputTokens),
        },
      };
    } catch (error) {
      console.warn("Claude Agent: API call failed, falling back to mock");
      const latencyMs = Date.now() - start;
      const output = this._generateWithMock(prompt);
      return {
        output,
        metrics: { modelId, inputTokens: null, outputTokens: null, latencyMs, estimatedCostUsd: null },
      };
    }
  }

  _generateWithMock(prompt) {
    const mockComponents = [
      `<template>
  <div class="flex items-center justify-center min-h-screen bg-slate-50">
    <div class="w-full max-w-lg">
      <div class="bg-white rounded-xl shadow-md p-8 border border-slate-200">
        <h3 class="text-xl font-semibold text-slate-900 mb-3">${prompt}</h3>
        <p class="text-slate-600 text-sm mb-6">This component was generated by Claude Agent</p>
        <div class="space-y-3">
          <input type="text" placeholder="Enter your input" class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:border-slate-500" />
          <button class="w-full bg-slate-900 hover:bg-slate-800 text-white font-medium py-2 rounded-lg transition">
            Submit
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Component generated by Claude Agent
</script>

<style scoped>
/* Tailwind styles applied via classes */
</style>`,
      `<template>
  <section class="bg-white">
    <div class="max-w-4xl mx-auto px-4 py-12">
      <div class="grid md:grid-cols-2 gap-8">
        <div class="space-y-4">
          <h2 class="text-3xl font-bold text-gray-900">${prompt}</h2>
          <p class="text-gray-600 leading-relaxed">Generated by Claude Agent with elegant design patterns</p>
          <button class="inline-flex items-center px-6 py-3 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition">
            Get Started
          </button>
        </div>
        <div class="bg-slate-100 rounded-lg h-64 flex items-center justify-center">
          <span class="text-slate-500">Preview Area</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// Component generated by Claude Agent
</script>

<style scoped>
/* Tailwind styles applied via classes */
</style>`,
    ];
    return mockComponents[Math.floor(Math.random() * mockComponents.length)];
  }
}
