import { BaseAgent } from "./BaseAgent.js";

export class GeminiAgent extends BaseAgent {
  constructor() {
    super("gemini", "Google Gemini");
    this.client = null;
  }

  async generate(prompt, modelId, image = null) {
    const start = Date.now();
    const output = this._generateWithMock(prompt);
    const latencyMs = Date.now() - start;
    return {
      output,
      metrics: { modelId, inputTokens: null, outputTokens: null, latencyMs, estimatedCostUsd: null },
    };
  }

  _generateWithMock(prompt) {
    const mockComponents = [
      `<template>
  <div class="bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 min-h-screen flex items-center">
    <div class="max-w-2xl mx-auto text-white px-4">
      <h1 class="text-5xl font-bold mb-4">${prompt}</h1>
      <p class="text-xl mb-8 text-blue-100">Generated by Gemini Agent with modern design</p>
      <div class="flex gap-4">
        <button class="px-8 py-3 bg-white text-blue-600 font-bold rounded-lg hover:bg-blue-50 transition">
          Explore
        </button>
        <button class="px-8 py-3 border-2 border-white text-white font-bold rounded-lg hover:bg-white hover:text-blue-600 transition">
          Learn More
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Component generated by Gemini Agent
</script>

<style scoped>
/* Tailwind styles applied via classes */
</style>`,
      `<template>
  <div class="min-h-screen bg-white">
    <nav class="bg-gray-50 border-b border-gray-200">
      <div class="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center">
        <h2 class="text-2xl font-bold text-gray-900">${prompt}</h2>
        <button class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600">
          Action
        </button>
      </div>
    </nav>
    <div class="max-w-6xl mx-auto px-4 py-12">
      <div class="grid md:grid-cols-3 gap-6">
        <div class="p-6 border border-gray-200 rounded-lg hover:shadow-lg transition">
          <h3 class="text-lg font-semibold mb-2">Feature One</h3>
          <p class="text-gray-600">Generated by Gemini with responsive layout</p>
        </div>
        <div class="p-6 border border-gray-200 rounded-lg hover:shadow-lg transition">
          <h3 class="text-lg font-semibold mb-2">Feature Two</h3>
          <p class="text-gray-600">Clean and modern design patterns</p>
        </div>
        <div class="p-6 border border-gray-200 rounded-lg hover:shadow-lg transition">
          <h3 class="text-lg font-semibold mb-2">Feature Three</h3>
          <p class="text-gray-600">Optimized for all screen sizes</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Component generated by Gemini Agent
</script>

<style scoped>
/* Tailwind styles applied via classes */
</style>`,
    ];
    return mockComponents[Math.floor(Math.random() * mockComponents.length)];
  }
}
